export const DEVICE_TYPE_LIST_REQUEST = "DEVICE_TYPE_LIST_REQUEST";
export const DEVICE_TYPE_LIST_SUCCESS = "DEVICE_TYPE_LIST_SUCCESS";
export const DEVICE_TYPE_LIST_FAIL = "DEVICE_TYPE_LIST_FAIL";
export const DEVICE_TYPE_LIST_RESET = "DEVICE_TYPE_LIST_RESET";

export const DEVICE_TYPE_CREATE_REQUEST = "DEVICE_TYPE_CREATE_REQUEST";
export const DEVICE_TYPE_CREATE_SUCCESS = "DEVICE_TYPE_CREATE_SUCCESS";
export const DEVICE_TYPE_CREATE_FAIL = "DEVICE_TYPE_CREATE_FAIL";
export const DEVICE_TYPE_CREATE_RESET = "DEVICE_TYPE_CREATE_RESET";

export const DEVICE_TYPE_DETAILS_REQUEST = "DEVICE_TYPE_DETAILS_REQUEST";
export const DEVICE_TYPE_DETAILS_SUCCESS = "DEVICE_TYPE_DETAILS_SUCCESS";
export const DEVICE_TYPE_DETAILS_FAIL = "DEVICE_TYPE_DETAILS_FAIL";
export const DEVICE_TYPE_DETAILS_RESET = "DEVICE_TYPE_DETAILS_RESET";

export const DEVICE_TYPE_UPDATE_REQUEST = "DEVICE_TYPE_UPDATE_REQUEST";
export const DEVICE_TYPE_UPDATE_SUCCESS = "DEVICE_TYPE_UPDATE_SUCCESS";
export const DEVICE_TYPE_UPDATE_FAIL = "DEVICE_TYPE_UPDATE_FAIL";
export const DEVICE_TYPE_UPDATE_RESET = "DEVICE_TYPE_UPDATE_RESET";

export const DEVICE_TYPE_DELETE_REQUEST = "DEVICE_TYPE_DELETE_REQUEST";
export const DEVICE_TYPE_DELETE_SUCCESS = "DEVICE_TYPE_DELETE_SUCCESS";
export const DEVICE_TYPE_DELETE_FAIL = "DEVICE_TYPE_DELETE_FAIL";
export const DEVICE_TYPE_DELETE_RESET = "DEVICE_TYPE_DELETE_RESET";

export const DEVICE_PURCHASE_LIST_REQUEST = "DEVICE_PURCHASE_LIST_REQUEST";
export const DEVICE_PURCHASE_LIST_SUCCESS = "DEVICE_PURCHASE_LIST_SUCCESS";
export const DEVICE_PURCHASE_LIST_FAIL = "DEVICE_PURCHASE_LIST_FAIL";

export const DEVICE_PURCHASE_CREATE_REQUEST = "DEVICE_PURCHASE_CREATE_REQUEST";
export const DEVICE_PURCHASE_CREATE_SUCCESS = "DEVICE_PURCHASE_CREATE_SUCCESS";
export const DEVICE_PURCHASE_CREATE_FAIL = "DEVICE_PURCHASE_CREATE_FAIL";
export const DEVICE_PURCHASE_CREATE_RESET = "DEVICE_PURCHASE_CREATE_RESET";

export const DEVICE_ONE_PURCHASE_DETAILS_REQUEST =
  "DEVICE_ONE_PURCHASE_DETAILS_REQUEST";
export const DEVICE_ONE_PURCHASE_DETAILS_SUCCESS =
  "DEVICE_ONE_PURCHASE_DETAILS_SUCCESS";
export const DEVICE_ONE_PURCHASE_DETAILS_FAIL =
  "DEVICE_ONE_PURCHASE_DETAILS_FAIL";
export const DEVICE_ONE_PURCHASE_DETAILS_RESET =
  "DEVICE_ONE_PURCHASE_DETAILS_RESET";

export const DEVICE_PURCHASE_UPDATE_REQUEST = "DEVICE_PURCHASE_UPDATE_REQUEST";
export const DEVICE_PURCHASE_UPDATE_SUCCESS = "DEVICE_PURCHASE_UPDATE_SUCCESS";
export const DEVICE_PURCHASE_UPDATE_FAIL = "DEVICE_PURCHASE_UPDATE_FAIL";
export const DEVICE_PURCHASE_UPDATE_RESET = "DEVICE_PURCHASE_UPDATE_RESET";

export const DEVICE_PURCHASE_DELETE_REQUEST = "DEVICE_PURCHASE_DELETE_REQUEST";
export const DEVICE_PURCHASE_DELETE_SUCCESS = "DEVICE_PURCHASE_DELETE_SUCCESS";
export const DEVICE_PURCHASE_DELETE_FAIL = "DEVICE_PURCHASE_DELETE_FAIL";
export const DEVICE_PURCHASE_DELETE_RESET = "DEVICE_PURCHASE_DELETE_RESET";

export const DEVICE_PROPERTIES_LIST_REQUEST = "DEVICE_PROPERTIES_LIST_REQUEST";
export const DEVICE_PROPERTIES_LIST_SUCCESS = "DEVICE_PROPERTIES_LIST_SUCCESS";
export const DEVICE_PROPERTIES_LIST_FAIL = "DEVICE_PROPERTIES_LIST_FAIL";
export const DEVICE_PROPERTIES_LIST_RESET = "DEVICE_PROPERTIES_LIST_RESET";

export const DEVICE_PROPERTIES_CREATE_REQUEST =
  "DEVICE_PROPERTIES_CREATE_REQUEST";
export const DEVICE_PROPERTIES_CREATE_SUCCESS =
  "DEVICE_PROPERTIES_CREATE_SUCCESS";
export const DEVICE_PROPERTIES_CREATE_FAIL = "DEVICE_PROPERTIES_CREATE_FAIL";
export const DEVICE_PROPERTIES_CREATE_RESET = "DEVICE_PROPERTIES_CREATE_RESET";

export const DEVICE_SERIAL_LIST_REQUEST = "DEVICE_SERIAL_LIST_REQUEST";
export const DEVICE_SERIAL_LIST_SUCCESS = "DEVICE_SERIAL_LIST_SUCCESS";
export const DEVICE_SERIAL_LIST_FAIL = "DEVICE_SERIAL_LIST_FAIL";
export const DEVICE_SERIAL_LIST_RESET = "DEVICE_SERIAL_LIST_RESET";

export const DEVICE_PROPERTIES_DETAILS_REQUEST =
  "DEVICE_PROPERTIES_DETAILS_REQUEST";
export const DEVICE_PROPERTIES_DETAILS_SUCCESS =
  "DEVICE_PROPERTIES_DETAILS_SUCCESS";
export const DEVICE_PROPERTIES_DETAILS_FAIL = "DEVICE_PROPERTIES_DETAILS_FAIL";
export const DEVICE_PROPERTIES_DETAILS_RESET =
  "DEVICE_PROPERTIES_DETAILS_RESET";

export const DEVICE_PROPERTIES_UPDATE_REQUEST =
  "DEVICE_PROPERTIES_UPDATE_REQUEST";
export const DEVICE_PROPERTIES_UPDATE_SUCCESS =
  "DEVICE_PROPERTIES_UPDATE_SUCCESS";
export const DEVICE_PROPERTIES_UPDATE_FAIL = "DEVICE_PROPERTIES_UPDATE_FAIL";
export const DEVICE_PROPERTIES_UPDATE_RESET = "DEVICE_PROPERTIES_UPDATE_RESET";

export const DEVICE_PROPERTIES_DELETE_REQUEST =
  "DEVICE_PROPERTIES_DELETE_REQUEST";
export const DEVICE_PROPERTIES_DELETE_SUCCESS =
  "DEVICE_PROPERTIES_DELETE_SUCCESS";
export const DEVICE_PROPERTIES_DELETE_FAIL = "DEVICE_PROPERTIES_DELETE_FAIL";
export const DEVICE_PROPERTIES_DELETE_RESET = "DEVICE_PROPERTIES_DELETE_RESET";

export const DEVICE_DETAILS_LIST_REQUEST = "DEVICE_DETAILS_LIST_REQUEST";
export const DEVICE_DETAILS_LIST_SUCCESS = "DEVICE_DETAILS_LIST_SUCCESS";
export const DEVICE_DETAILS_LIST_FAIL = "DEVICE_DETAILS_LIST_FAIL";
export const DEVICE_DETAILS_LIST_RESET = "DEVICE_DETAILS_LIST_RESET";

export const DEVICE_CONSUME_CREATE_REQUEST = "DEVICE_CONSUME_CREATE_REQUEST";
export const DEVICE_CONSUME_CREATE_SUCCESS = "DEVICE_CONSUME_CREATE_SUCCESS";
export const DEVICE_CONSUME_CREATE_FAIL = "DEVICE_CONSUME_CREATE_FAIL";
export const DEVICE_CONSUME_CREATE_RESET = "DEVICE_CONSUME_CREATE_RESET";

export const DEVICE_PURCHASE_ASSIGN_UPDATE_REQUEST =
  "DEVICE_PURCHASE_ASSIGN_UPDATE_REQUEST";
export const DEVICE_PURCHASE_ASSIGN_UPDATE_SUCCESS =
  "DEVICE_PURCHASE_ASSIGN_UPDATE_SUCCESS";
export const DEVICE_PURCHASE_ASSIGN_UPDATE_FAIL =
  "DEVICE_PURCHASE_ASSIGN_UPDATE_FAIL";
export const DEVICE_PURCHASE_ASSIGN_UPDATE_RESET =
  "DEVICE_PURCHASE_ASSIGN_UPDATE_RESET";

export const DEVICE_ASSIGN_LIST_REQUEST = "DEVICE_ASSIGN_LIST_REQUEST";
export const DEVICE_ASSIGN_LIST_SUCCESS = "DEVICE_ASSIGN_LIST_SUCCESS";
export const DEVICE_ASSIGN_LIST_FAIL = "DEVICE_ASSIGN_LIST_FAIL";
export const DEVICE_ASSIGN_LIST_RESET = "DEVICE_ASSIGN_LIST_RESET";

export const DEVICE_CONSUME_DELETE_REQUEST = "DEVICE_CONSUME_DELETE_REQUEST";
export const DEVICE_CONSUME_DELETE_SUCCESS = "DEVICE_CONSUME_DELETE_SUCCESS";
export const DEVICE_CONSUME_DELETE_FAIL = "DEVICE_CONSUME_DELETE_FAIL";
export const DEVICE_CONSUME_DELETE_RESET = "DEVICE_CONSUME_DELETE_RESET";

export const DEVICE_SEARCH_REQUEST = "DEVICE_SEARCH_REQUEST";
export const DEVICE_SEARCH_SUCCESS = "DEVICE_SEARCH_SUCCESS";
export const DEVICE_SEARCH_FAIL = "DEVICE_SEARCH_FAIL";

export const BRAND_LIST_REQUEST = "BRAND_LIST_REQUEST";
export const BRAND_LIST_SUCCESS = "BRAND_LIST_SUCCESS";
export const BRAND_LIST_FAIL = "BRAND_LIST_FAIL";

export const DEVICE_PRO_ALL_LIST_REQUEST = "DEVICE_PRO_ALL_LIST_REQUEST";
export const DEVICE_PRO_ALL_LIST_SUCCESS = "DEVICE_PRO_ALL_LIST_SUCCESS";
export const DEVICE_PRO_ALL_LIST_FAIL = "DEVICE_PRO_ALL_LIST_FAIL";

export const DEVICE_HOME_ALL_LIST_REQUEST = "DEVICE_HOME_ALL_LIST_REQUEST";
export const DEVICE_HOME_ALL_LIST_SUCCESS = "DEVICE_HOME_ALL_LIST_SUCCESS";
export const DEVICE_HOME_ALL_LIST_FAIL = "DEVICE_HOME_ALL_LIST_FAIL";

export const DEVICE_PROPERTIES_ADD_REQUEST = "DEVICE_PROPERTIES_ADD_REQUEST";
export const DEVICE_PROPERTIES_ADD_SUCCESS = "DEVICE_PROPERTIES_ADD_SUCCESS";
export const DEVICE_PROPERTIES_ADD_FAIL = "DEVICE_PROPERTIES_ADD_FAIL";
export const DEVICE_PROPERTIES_ADD_RESET = "DEVICE_PROPERTIES_ADD_RESET";

export const DEVICE_PROPERTIES_REMOVE_REQUEST =
  "DEVICE_PROPERTIES_REMOVE_REQUEST";
export const DEVICE_PROPERTIES_REMOVE_SUCCESS =
  "DEVICE_PROPERTIES_REMOVE_SUCCESS";
export const DEVICE_PROPERTIES_REMOVE_FAIL = "DEVICE_PROPERTIES_REMOVE_FAIL";
export const DEVICE_PROPERTIES_REMOVE_RESET = "DEVICE_PROPERTIES_REMOVE_RESET";
