export const SOURCE_LIST_REQUEST = "SOURCE_LIST_REQUEST";
export const SOURCE_LIST_SUCCESS = "SOURCE_LIST_SUCCESS";
export const SOURCE_LIST_FAIL = "SOURCE_LIST_FAIL";

export const SOURCE_CREATE_REQUEST = "SOURCE_CREATE_REQUEST";
export const SOURCE_CREATE_SUCCESS = "SOURCE_CREATE_SUCCESS";
export const SOURCE_CREATE_FAIL = "SOURCE_CREATE_FAIL";
export const SOURCE_CREATE_RESET = "SOURCE_CREATE_RESET";

export const SOURCE_DETAILS_REQUEST = "SOURCE_DETAILS_REQUEST";
export const SOURCE_DETAILS_SUCCESS = "SOURCE_DETAILS_SUCCESS";
export const SOURCE_DETAILS_FAIL = "SOURCE_DETAILS_FAIL";
export const SOURCE_DETAILS_RESET = "SOURCE_DETAILS_RESET";

export const SOURCE_UPDATE_REQUEST = "SOURCE_UPDATE_REQUEST";
export const SOURCE_UPDATE_SUCCESS = "SOURCE_UPDATE_SUCCESS";
export const SOURCE_UPDATE_FAIL = "SOURCE_UPDATE_FAIL";
export const SOURCE_UPDATE_RESET = "SOURCE_UPDATE_RESET";

export const SOURCE_DELETE_REQUEST = "SOURCE_DELETE_REQUEST";
export const SOURCE_DELETE_SUCCESS = "SOURCE_DELETE_SUCCESS";
export const SOURCE_DELETE_FAIL = "SOURCE_DELETE_FAIL";
export const SOURCE_DELETE_RESET = "SOURCE_DELETE_RESET";
