export const STATIONARY_PURCHASE_LIST_REQUEST =
  "STATIONARY_PURCHASE_LIST_REQUEST";
export const STATIONARY_PURCHASE_LIST_SUCCESS =
  "STATIONARY_PURCHASE_LIST_SUCCESS";
export const STATIONARY_PURCHASE_LIST_FAIL = "STATIONARY_PURCHASE_LIST_FAIL";

export const STATIONARY_PURCHASE_CREATE_REQUEST =
  "STATIONARY_PURCHASE_CREATE_REQUEST";
export const STATIONARY_PURCHASE_CREATE_SUCCESS =
  "STATIONARY_PURCHASE_CREATE_SUCCESS";
export const STATIONARY_PURCHASE_CREATE_FAIL =
  "STATIONARY_PURCHASE_CREATE_FAIL";
export const STATIONARY_PURCHASE_CREATE_RESET =
  "SSTATIONARY_PURCHASE_CREATE_RESET";

export const STATIONARY_PURCHASE_DETAILS_REQUEST =
  "SSTATIONARY_PURCHASE_DETAILS_REQUEST";
export const STATIONARY_PURCHASE_DETAILS_SUCCESS =
  "STATIONARY_PURCHASE_DETAILS_SUCCESS";
export const STATIONARY_PURCHASE_DETAILS_FAIL =
  "STATIONARY_PURCHASE_DETAILS_FAIL";
export const STATIONARY_PURCHASE_DETAILS_RESET =
  "STATIONARY_PURCHASE_DETAILS_RESET";

export const STATIONARY_ONE_PURCHASE_DETAILS_REQUEST =
  "STATIONARY_ONE_PURCHASE_DETAILS_REQUEST";
export const STATIONARY_ONE_PURCHASE_DETAILS_SUCCESS =
  "STATIONARY_ONE_PURCHASE_DETAILS_SUCCESS";
export const STATIONARY_ONE_PURCHASE_DETAILS_FAIL =
  "STATIONARY_ONE_PURCHASE_DETAILS_FAIL";
export const STATIONARY_ONE_PURCHASE_DETAILS_RESET =
  "STATIONARY_ONE_PURCHASE_DETAILS_RESET";

export const STATIONARY_PURCHASE_UPDATE_REQUEST =
  "STATIONARY_PURCHASE_UPDATE_REQUEST";
export const STATIONARY_PURCHASE_UPDATE_SUCCESS =
  "STATIONARY_PURCHASE_UPDATE_SUCCESS";
export const STATIONARY_PURCHASE_UPDATE_FAIL =
  "STATIONARY_PURCHASE_UPDATE_FAIL";
export const STATIONARY_PURCHASE_UPDATE_RESET =
  "STATIONARY_PURCHASE_UPDATE_RESET";

export const STATIONARY_PURCHASE_DELETE_REQUEST =
  "STATIONARY_PURCHASE_DELETE_REQUEST";
export const STATIONARY_PURCHASE_DELETE_SUCCESS =
  "STATIONARY_PURCHASE_DELETE_SUCCESS";
export const STATIONARY_PURCHASE_DELETE_FAIL =
  "STATIONARY_PURCHASE_DELETE_FAIL";
export const STATIONARY_PURCHASE_DELETE_RESET =
  "STATIONARY_PURCHASE_DELETE_RESET";

export const GET_ALL_STATIONARY_REQUEST = "GET_ALL_STATIONARY_REQUEST";
export const GET_ALL_STATIONARY_SUCCESS = "GET_ALL_STATIONARY_SUCCESS";
export const GET_ALL_STATIONARY_FAIL = "GET_ALL_STATIONARY_FAIL";

export const GET_ONE_ALL_STATIONARY_REQUEST = "GET_ONE_ALL_STATIONARY_REQUEST";
export const GET_ONE_ALL_STATIONARY_SUCCESS = "GET_ONE_ALL_STATIONARY_SUCCESS";
export const GET_ONE_ALL_STATIONARY_FAIL = "GET_ONE_ALL_STATIONARY_FAIL";

export const STATIONARY_ASSIGN_REQUEST = "STATIONARY_ASSIGN_REQUEST";
export const STATIONARY_ASSIGN_SUCCESS = "STATIONARY_ASSIGN_SUCCESS";
export const STATIONARY_ASSIGN_FAIL = "STATIONARY_ASSIGN_FAIL";
export const STATIONARY_ASSIGN_RESET = "STATIONARY_ASSIGN_RESET";

export const SEARCH_STATIONARY_ASSIGN_REQUEST =
  "SEARCH_STATIONARY_ASSIGN_REQUEST";
export const SEARCH_STATIONARY_ASSIGN_SUCCESS =
  "SEARCH_STATIONARY_ASSIGN_SUCCESS";
export const SEARCH_STATIONARY_ASSIGN_FAIL = "SEARCH_STATIONARY_ASSIGN_FAIL";
export const SEARCH_STATIONARY_ASSIGN_RESET = "SEARCH_STATIONARY_ASSIGN_RESET";

export const STATIONARY_TYPE_TOTAL_REQUEST = "STATIONARY_TYPE_TOTAL_REQUEST";
export const STATIONARY_TYPE_TOTAL_SUCCESS = "STATIONARY_TYPE_TOTAL_SUCCESS";
export const STATIONARY_TYPE_TOTAL_FAIL = "STATIONARY_TYPE_TOTAL_FAIL";
export const STATIONARY_TYPE_TOTAL_RESET = "STATIONARY_TYPE_TOTAL_RESET";

export const SEARCH_STATIONARY_ASSIGN_EDIT_REQUEST =
  "SEARCH_STATIONARY_ASSIGN_EDIT_REQUEST";
export const SEARCH_STATIONARY_ASSIGN_EDIT_SUCCESS =
  "SEARCH_STATIONARY_ASSIGN_EDIT_SUCCESS";
export const SEARCH_STATIONARY_ASSIGN_EDIT_FAIL =
  "SEARCH_STATIONARY_ASSIGN_EDIT_FAIL";
export const SEARCH_STATIONARY_ASSIGN_EDIT_RESET =
  "SEARCH_STATIONARY_ASSIGN_EDIT_RESET";

export const STATIONARY_ASSIGN_UPDATE_REQUEST =
  "STATIONARY_ASSIGN_UPDATE_REQUEST";
export const STATIONARY_ASSIGN_UPDATE_SUCCESS =
  "STATIONARY_ASSIGN_UPDATE_SUCCESS";
export const STATIONARY_ASSIGN_UPDATE_FAIL = "STATIONARY_ASSIGN_UPDATE_FAIL";
export const STATIONARY_ASSIGN_UPDATE_RESET = "STATIONARY_ASSIGN_UPDATE_RESET";

export const STATIONARY_ASSIGN_DELETE_REQUEST =
  "STATIONARY_ASSIGN_DELETE_REQUEST";
export const STATIONARY_ASSIGN_DELETE_SUCCESS =
  "STATIONARY_ASSIGN_DELETE_SUCCESS";
export const STATIONARY_ASSIGN_DELETE_FAIL = "STATIONARY_ASSIGN_DELETE_FAIL";
export const STATIONARY_ASSIGN_DELETE_RESET = "STATIONARY_ASSIGN_DELETE_RESET";
