export const STATIONAR_TYPE_LIST_REQUEST = "STATIONAR_TYPE_LIST_REQUEST";
export const STATIONAR_TYPE_LIST_SUCCESS = "STATIONAR_TYPE_LIST_SUCCESS";
export const STATIONAR_TYPE_LIST_FAIL = "STATIONAR_TYPE_LIST_FAIL";

export const STATIONAR_TYPE_CREATE_REQUEST = "STATIONAR_TYPE_CREATE_REQUEST";
export const STATIONAR_TYPE_CREATE_SUCCESS = "STATIONAR_TYPE_CREATE_SUCCESS";
export const STATIONAR_TYPE_CREATE_FAIL = "STATIONAR_TYPE_CREATE_FAIL";
export const STATIONAR_TYPE_CREATE_RESET = "STATIONAR_TYPE_CREATE_RESET";

export const STATIONAR_TYPE_UPDATE_REQUEST = "STATIONAR_TYPE_UPDATE_REQUEST";
export const STATIONAR_TYPE_UPDATE_SUCCESS = "STATIONAR_TYPE_UPDATE_SUCCESS";
export const STATIONAR_TYPE_UPDATE_FAIL = "STATIONAR_TYPE_UPDATE_FAIL";
export const STATIONAR_TYPE_UPDATE_RESET = "STATIONAR_TYPE_UPDATE_RESET";

export const STATIONAR_TYPE_DETAILS_REQUEST = "STATIONAR_TYPE_DETAILS_REQUEST";
export const STATIONAR_TYPE_DETAILS_SUCCESS = "STATIONAR_TYPE_DETAILS_SUCCESS";
export const STATIONAR_TYPE_DETAILS_FAIL = "STATIONAR_TYPE_DETAILS_FAIL";
export const STATIONAR_TYPE_DETAILS_RESET = "STATIONAR_TYPE_DETAILS_RESET";

export const STATIONAR_TYPE_DELETE_REQUEST = "STATIONAR_TYPE_DELETE_REQUEST";
export const STATIONAR_TYPE_DELETE_SUCCESS = "STATIONAR_TYPE_DELETE_SUCCESS";
export const STATIONAR_TYPE_DELETE_FAIL = "STATIONAR_TYPE_DELETE_FAIL";
export const STATIONAR_TYPE_DELETE_RESET = "STATIONAR_TYPE_DELETE_RESET";
